import Contact from "../models/ContactModel.js";
import Conversation from "../models/ConversationModel.js";
import LLMService from "../services/LLMService.js";
import { buildPersonalizedMessagePrompt } from "./buildPersonalizedMessagePrompt.js";

/**
 * Generates a personalized check-in notification for a user based on recent conversations and important dates.
 * @param {string} userId - The unique identifier for the user.
 * @param {string} contactId - The unique identifier for the contact.
 * @returns {Promise<object>} - An object containing the notification header and message generated by the LLM.
 */
export const generateCheckInNotificationMessage = async (userId, contactId) => {
  try {
    // Fetch conversations
    const conversations = await Conversation.find({ userId, contactId })
      .select("checkInDetails date -_id")
      .sort({ date: -1 });

    // Retrieve the contact's details
    const contact = await Contact.findById(contactId).select(
      "name importantDates lastCheckInDate"
    );
    if (!contact) {
      throw new Error("Contact not found.");
    }

    // Construct the prompt
    const { notificationPrompt } = buildPersonalizedMessagePrompt(
      contact,
      conversations
    );

    // Call the LLM service
    const response = await LLMService.callLLM(notificationPrompt);

    // Process the response to extract header and message
    const [headerLine, messageLine] = response.split("\n").filter(Boolean);
    const notificationHeader = headerLine
      .replace("Notification Header: ", "")
      .trim();
    const notificationMessage = messageLine
      .replace("Notification Message: ", "")
      .trim();

    return { notificationHeader, notificationMessage };
  } catch (error) {
    console.error("Error generating check-in notification:", error);
    throw new Error("Failed to generate check-in notification.");
  }
};
